import { Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import Nav from "./_components/nav/Nav";

const dmSans = DM_Sans({subsets:['latin'], weight:['100', '200', '300', '400', '500', '700']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: {locale} }) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={dmSans.className}>
        <NextIntlClientProvider messages={messages}>
          <Nav locale={locale}/>
        {children}

        </NextIntlClientProvider>
      
      </body>
    </html>
  );
}
